export const MRF_SEED = [
  { id: 1, mrf_number: 'MRF-ANT-2025-00001', date: '2025-01-15', project_code: 'ANT',
    location: 'Block A', zone: 'Basement', requested_by: 'Ahmed Al-Rashid',
    material_desc: 'Ready Mix Concrete M40 — Foundations', qty: 500, unit: 'CUM',
    required_on_site: '2025-01-22', priority: 'Critical', related_activity: 'Foundation Pouring',
    remarks: 'Urgent — piling complete. 3rd party test required.',
    mat_spec: 'M40 Ready Mix Concrete', brand: 'Gulf Concrete Co.', grade: 'M40', code_ref: 'BS EN 206',
    sample_ref: 'SMPL-2025-001', subm_ref: 'MS-2025-001', subm_status: 'Approved',
    consult_approval_date: '2025-01-10', ifc_drawing: 'IFC-STR-001', shop_drawing: 'SD-STR-001', drawing_rev: 'Rev 03',
    wbs_code: '1.1.2', activity_id: 'A1010', activity_name: 'Basement Foundation Pour',
    programme_ref: 'P6-1010', planned_start: '2025-01-20', planned_finish: '2025-01-28',
    lead_time_days: 7, latest_raise_date: '2025-01-15',
    approval_status: 'Approved', approval_remarks: '', approval_date: '2025-01-16', approval_by: 'Omar Shaikh',
    supplier: 'Gulf Concrete Co.', quotation_ref: 'QT-2025-0045', po_number: 'PO-ANT-2025-00012',
    po_date: '2025-01-17', po_amount: 125000, expected_delivery: '2025-01-22',
    delivered_qty: 500, dn_number: 'DN-045', delivery_date: '2025-01-22',
    store_received: true, store_received_date: '2025-01-22', site_received: true,
    mir_number: 'MIR-ANT-2025-00001', mir_raised_date: '2025-01-22', mir_submitted_date: '2025-01-23',
    mir_approved_date: '2025-01-24', mir_rejected_date: null, mir_resub_count: 0,
    mir_result: 'Approved', mir_remarks: '', site_release_date: '2025-01-24',
    site_status: 'Approved for Use' },

  { id: 2, mrf_number: 'MRF-ANT-2025-00002', date: '2025-01-18', project_code: 'ANT',
    location: 'Block B', zone: 'Ground Floor', requested_by: 'Sara Qureshi',
    material_desc: 'TMT Rebar 16mm Grade 60', qty: 45, unit: 'MT',
    required_on_site: '2025-01-28', priority: 'High', related_activity: 'Column Reinforcement GF',
    remarks: 'Confirm mill certificates before delivery.',
    mat_spec: 'High Yield Deformed Bar', brand: 'Emirates Steel', grade: 'Grade 60', code_ref: 'ASTM A615',
    sample_ref: 'SMPL-2025-002', subm_ref: 'MS-2025-002', subm_status: 'Approved',
    consult_approval_date: '2025-01-12', ifc_drawing: 'IFC-STR-010', shop_drawing: 'SD-STR-010', drawing_rev: 'Rev 02',
    wbs_code: '1.2.1', activity_id: 'A1210', activity_name: 'GF Column Reinforcement',
    programme_ref: 'P6-1210', planned_start: '2025-01-28', planned_finish: '2025-02-05',
    lead_time_days: 10, latest_raise_date: '2025-01-18',
    approval_status: 'Approved', approval_remarks: '', approval_date: '2025-01-19', approval_by: 'Omar Shaikh',
    supplier: 'Emirates Steel', quotation_ref: 'QT-2025-0052', po_number: 'PO-ANT-2025-00018',
    po_date: '2025-01-20', po_amount: 92000, expected_delivery: '2025-01-28',
    delivered_qty: 30, dn_number: 'DN-062', delivery_date: '2025-01-28',
    store_received: true, store_received_date: '2025-01-28', site_received: false,
    mir_number: 'MIR-ANT-2025-00002', mir_raised_date: '2025-01-29', mir_submitted_date: '2025-01-30',
    mir_approved_date: '2025-01-31', mir_rejected_date: null, mir_resub_count: 0,
    mir_result: 'Approved', mir_remarks: '', site_release_date: '2025-01-31',
    site_status: 'Partially Delivered' },

  { id: 3, mrf_number: 'MRF-MRS-2025-00001', date: '2025-01-20', project_code: 'MRS',
    location: 'Tower C', zone: 'Level 3', requested_by: 'Khalid Mansoor',
    material_desc: 'SBS Waterproofing Membrane Type A', qty: 200, unit: 'SQM',
    required_on_site: '2025-02-05', priority: 'High', related_activity: 'Basement Waterproofing L3',
    remarks: 'Check batch numbers against approved submittal.',
    mat_spec: 'SBS Modified Bitumen Membrane 4mm', brand: 'Sika / Approved Equal', grade: 'Type A', code_ref: 'ASTM D6163',
    sample_ref: 'SMPL-2025-003', subm_ref: 'MS-2025-003', subm_status: 'Approved',
    consult_approval_date: '2025-01-14', ifc_drawing: 'IFC-WP-001', shop_drawing: null, drawing_rev: 'Rev 01',
    wbs_code: '2.1.3', activity_id: 'B2030', activity_name: 'Basement Waterproofing L3',
    programme_ref: 'P6-2030', planned_start: '2025-02-04', planned_finish: '2025-02-12',
    lead_time_days: 16, latest_raise_date: '2025-01-20',
    approval_status: 'Submitted', approval_remarks: '', approval_date: null, approval_by: null,
    supplier: null, quotation_ref: null, po_number: null,
    po_date: null, po_amount: null, expected_delivery: null,
    delivered_qty: 0, dn_number: null, delivery_date: null,
    store_received: false, store_received_date: null, site_received: false,
    mir_number: null, mir_raised_date: null, mir_submitted_date: null,
    mir_approved_date: null, mir_rejected_date: null, mir_resub_count: 0,
    mir_result: null, mir_remarks: '', site_release_date: null,
    site_status: 'Not Ordered' },

  { id: 4, mrf_number: 'MRF-ANT-2025-00003', date: '2025-01-22', project_code: 'ANT',
    location: 'Tower D', zone: 'Level 1', requested_by: 'Nadia Hassan',
    material_desc: 'Aluminium Curtain Wall System — Type CW-01', qty: 320, unit: 'SQM',
    required_on_site: '2025-02-10', priority: 'Critical', related_activity: 'Curtain Wall L1',
    remarks: 'Long lead item — fabrication required.',
    mat_spec: 'Aluminium Curtain Wall CW-01', brand: 'Schuco / Approved Equal', grade: null, code_ref: 'BS 8000',
    sample_ref: null, subm_ref: 'MS-2025-004', subm_status: 'Pending',
    consult_approval_date: null, ifc_drawing: 'IFC-FAC-001', shop_drawing: null, drawing_rev: 'Rev 00',
    wbs_code: '1.3.1', activity_id: 'A3010', activity_name: 'Curtain Wall Installation L1',
    programme_ref: 'P6-3010', planned_start: '2025-02-08', planned_finish: '2025-03-15',
    lead_time_days: 19, latest_raise_date: '2025-01-22',
    approval_status: 'Draft', approval_remarks: '', approval_date: null, approval_by: null,
    supplier: null, quotation_ref: null, po_number: null,
    po_date: null, po_amount: null, expected_delivery: null,
    delivered_qty: 0, dn_number: null, delivery_date: null,
    store_received: false, store_received_date: null, site_received: false,
    mir_number: null, mir_raised_date: null, mir_submitted_date: null,
    mir_approved_date: null, mir_rejected_date: null, mir_resub_count: 0,
    mir_result: null, mir_remarks: '', site_release_date: null,
    site_status: 'Not Ordered' },

  { id: 5, mrf_number: 'MRF-MRS-2025-00002', date: '2025-01-25', project_code: 'MRS',
    location: 'Tower C', zone: 'Rooftop', requested_by: 'James Wu',
    material_desc: 'Chilled Water Pipe Insulation 50mm', qty: 850, unit: 'LM',
    required_on_site: '2025-02-15', priority: 'Medium', related_activity: 'MEP Insulation Works',
    remarks: 'Coordinate with MEP sub-contractor schedule.',
    mat_spec: 'Armaflex Class O 50mm', brand: 'Armacell', grade: null, code_ref: 'ASTM C534',
    sample_ref: 'SMPL-2025-005', subm_ref: 'MS-2025-005', subm_status: 'Approved',
    consult_approval_date: '2025-01-22', ifc_drawing: 'IFC-MEP-005', shop_drawing: null, drawing_rev: 'Rev 01',
    wbs_code: '2.4.1', activity_id: 'B4010', activity_name: 'MEP Insulation Works',
    programme_ref: 'P6-4010', planned_start: '2025-02-12', planned_finish: '2025-02-28',
    lead_time_days: 21, latest_raise_date: '2025-01-25',
    approval_status: 'Approved', approval_remarks: '', approval_date: '2025-01-26', approval_by: 'Omar Shaikh',
    supplier: 'Armacell Gulf', quotation_ref: 'QT-2025-0071', po_number: 'PO-MRS-2025-00005',
    po_date: '2025-01-28', po_amount: 38500, expected_delivery: '2025-02-14',
    delivered_qty: 0, dn_number: null, delivery_date: null,
    store_received: false, store_received_date: null, site_received: false,
    mir_number: null, mir_raised_date: null, mir_submitted_date: null,
    mir_approved_date: null, mir_rejected_date: null, mir_resub_count: 0,
    mir_result: null, mir_remarks: '', site_release_date: null,
    site_status: 'Ordered' },
]

export const LOCATIONS = ['Block A', 'Block B', 'Tower C', 'Tower D', 'Pier 4', 'Pier 5', 'West Wing']
export const ZONES = ['Basement', 'Ground Floor', 'Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5', 'Rooftop', 'Deck Level']
export const UNITS = ['CUM', 'MT', 'NOS', 'SQM', 'LM', 'BAG', 'KG', 'TON', 'SET', 'EA', 'LT']
export const PRIORITIES = ['Critical', 'High', 'Medium', 'Low']
export const SITE_STATUSES = ['Not Ordered', 'Ordered', 'Partially Delivered', 'Delivered', 'Under Inspection', 'Approved for Use', 'Rejected', 'Used at Site']
export const SUBM_STATUSES = ['Pending', 'Submitted', 'Approved', 'Rejected']
export const APPROVAL_STATUSES = ['Draft', 'Submitted', 'Approved', 'Rejected', 'On Hold', 'Revised']
